# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('smoke', models.IntegerField()),
            ],
        ),
    ]
