# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='h_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='source',
            field=models.IntegerField(default=0),
        ),
    ]
