# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_data_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='data',
            name='day',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='data',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='month',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='data',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
